name: Build and Test
on: [push]
jobs:
  build:
    runs-on: windows-10
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet packages
      run: nuget restore VMagicMirror.sln
    - name: Build
      run: msbuild VMagicMirror.sln /p:Configuration=Debug
    - name: Test
      run: vstest.console.exe /Platform:x64 /Framework:.NETFramework,Version=v4.7.2 /Logger:console VMagicMirrorTests.dll
